{
    "name": "Illuminate\\Exception\\SymfonyDisplayer",
    "line": 6,
    "short_desc": "",
    "long_desc": "",
    "hint": null,
    "tags": [

    ],
    "namespace": "Illuminate\\Exception",
    "file": "\/media\/sf_Code\/Laravel\/api-gen\/src\/Illuminate\/Exception\/SymfonyDisplayer.php",
    "hash": "af6b0ddf633b19fe0e00ed2e0bacf830321e1ab0",
    "parent": null,
    "modifiers": 0,
    "is_trait": false,
    "is_interface": false,
    "aliases": {
        "Exception": "Exception",
        "ExceptionHandler": "Symfony\\Component\\Debug\\ExceptionHandler"
    },
    "errors": [

    ],
    "interfaces": {
        "Illuminate\\Exception\\ExceptionDisplayerInterface": "Illuminate\\Exception\\ExceptionDisplayerInterface"
    },
    "properties": [

    ],
    "methods": {
        "__construct": {
            "name": "__construct",
            "line": 21,
            "short_desc": "Create a new Symfony exception displayer.",
            "long_desc": "",
            "hint": [
                [
                    "void",
                    false
                ]
            ],
            "hint_desc": "",
            "tags": [

            ],
            "modifiers": "1",
            "is_by_ref": "",
            "exceptions": [

            ],
            "errors": [

            ],
            "parameters": {
                "symfony": {
                    "name": "symfony",
                    "line": 21,
                    "short_desc": "",
                    "long_desc": null,
                    "hint": [
                        [
                            "Symfony\\Component\\Debug\\ExceptionHandler",
                            false
                        ]
                    ],
                    "tags": [

                    ],
                    "modifiers": "ExceptionHandler",
                    "default": null,
                    "is_by_ref": false
                }
            }
        },
        "display": {
            "name": "display",
            "line": 31,
            "short_desc": "Display the given exception to the user.",
            "long_desc": "",
            "hint": null,
            "hint_desc": null,
            "tags": [

            ],
            "modifiers": "1",
            "is_by_ref": "",
            "exceptions": [

            ],
            "errors": [

            ],
            "parameters": {
                "exception": {
                    "name": "exception",
                    "line": 31,
                    "short_desc": "",
                    "long_desc": null,
                    "hint": [
                        [
                            "Exception",
                            false
                        ]
                    ],
                    "tags": [

                    ],
                    "modifiers": "Exception",
                    "default": null,
                    "is_by_ref": false
                }
            }
        }
    },
    "constants": [

    ]
}